parser: "@typescript-eslint/parser"
extends:
  - "plugin:@typescript-eslint/recommended"
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  "@typescript-eslint/indent": off
  "@typescript-eslint/no-empty-function": off
