version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test:ci
      - run:
          command: npm run lint:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results/junit/junit.xml
      - store_artifacts:
          path: test-results/eslint/eslint.xml
      - store_artifacts:
          path: coverage
